### ISSUE TITLE
Still maintained? + Localization support

### ISSUE THREAD

**Issue by DannyBen** [HCLarsen/devise-uncommon_password#11]
Is this gem still maintained?

If so, it would be great if you can allow localization of the error message.

This block

https://github.com/HCLarsen/devise-uncommon_password/blob/cca8f40d05b4136fee5e053a71fd5bcffc38dd1e/lib/devise/uncommon_password/model.rb#L33-L37

Should probably just have something like:

```ruby
errors.add(:password, :common)
```

Which will just allow us to define the message in a localization file:

```ruby
# config/locales/activerecord.en.yml
en:
  activerecord: 
    errors:
      models:
        user:
          attributes:
            password:
              common: "must not be a commonly used password"
```

**Comment by HCLarsen** [comment]
That's a good idea. I'll look into this.

**Comment by willianveiga** [comment]
Once it's fixed, I can add the brazilian portuguese (pt-BR) translation. :smile:
