### ISSUE TITLE
Rails 7.1 support

### ISSUE THREAD

**Issue by vitaliiorlov** [HCLarsen/devise-uncommon_password#58]
Hi!
Rails 7.1 was released on October 5.
Could you update the gem to support this version?
Thanks!

[Rails 7.1: Dockerfiles, BYO Authentication, More Async Queries, and more!](https://rubyonrails.org/2023/10/5/Rails-7-1-0-has-been-released)

**Comment by HCLarsen** [comment]
Updated with V0.4.5.
